build: test pipeline

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -32,11 +32,17 @@ jobs:
       - name: Test
         run: make test
 
-      # Verify that we can create the release package.
-      - name: Verify Release
+      # Create and verify the release.
+      - name: Create and Verify Release
         run: |
           make release
-          test -f "./release/chatgpt-diagrams-*.zip"
+          test -n "$(find ./release -maxdepth 1 -name 'chatgpt-diagrams-*.zip' -print -quit)" || echo "cannot find release"; exit 1
+          then
+            echo "release exists..."
+          else
+            echo "cannot find release..."
+            exit 1
+          fi
 
       # Upload extension artifact.
       - name: Upload Extension Artifact
@@ -52,4 +58,4 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
-          package-name: chatgp4-diagrams-extension
+          package-name: chatgpt-diagrams-extension
diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -30,8 +30,7 @@ jobs:
     - name: Verify Release
       run: |
         make release
-        ls ./release
-        if test -n "$(find ./release -maxdepth 1 -name 'chatgpt-diagrams-*.zip' -print -quit)";
+        test -n "$(find ./release -maxdepth 1 -name 'chatgpt-diagrams-*.zip' -print -quit)" || echo "cannot find release"; exit 1
         then
           echo "release exists..."
         else
