build: check release exists

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -30,4 +30,11 @@ jobs:
     - name: Verify Release
       run: |
         make release
-        test -f "./release/chatgpt-diagrams-*.zip"
+        ls ./release
+        if test -n "$(find ./release -maxdepth 1 -name 'chatgpt-diagrams-*.zip' -print -quit)";
+        then
+          echo "release exists..."
+        else
+          echo "cannot find release..."
+          exit 1
+        fi
